image:
    name: tonyzhang/xenial-builder:2.0
    entrypoint: [""]

stages:
    - build
    - release

build_all:
    stage: build
    script:
      - |
        echo "Hello, $GITLAB_USER_LOGIN!"
        /usr/lib/qt-new/bin/qmake LIBS+=-L/usr/local/lib \
            CONFIG+=release CONFIG+=optimize_full mychartapp.pro
        make
        echo "Create binary tarball"
        mkdir appdir; mv mychartapp appdir; cd appdir;
        /tmp/squashfs-root/AppRun mychartapp \
          -qmake=/usr/lib/qt-new/bin/qmake -bundle-non-qt-libs -no-translations
        strip --strip-unneeded mychartapp
        cd ..; tar cvf chart-app_${CI_COMMIT_SHORT_SHA}.orig.tar.bz2 appdir
        echo "Create self-extractable script"
        makeself --notemp --nox11 appdir chart-app_${CI_COMMIT_SHORT_SHA}.run \
          "My Qt App with QtCharts and GSL Fitting" ./mychartapp
    artifacts:
        paths:
            - chart-app_${CI_COMMIT_SHORT_SHA}.orig.tar.bz2
            - chart-app_${CI_COMMIT_SHORT_SHA}.run
        expire_in: 1 week

release:
    only:
        - tags
    stage: release
    script:
        - |
          echo "New release: $CI_COMMIT_TAG."
          mv chart-app_${CI_COMMIT_SHORT_SHA}.orig.tar.bz2 chart-app_${CI_COMMIT_TAG}.orig.tar.bz2
          mv chart-app_${CI_COMMIT_SHORT_SHA}.run chart-app_${CI_COMMIT_TAG}.run
    artifacts:
        paths:
            - chart-app_${CI_COMMIT_TAG}.orig.tar.bz2
            - chart-app_${CI_COMMIT_TAG}.run
        expire_in: 1 week
