name: Build Qt Projects on Linux

on: [ push ]

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build a Qt App
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build with qt-app-builder
        uses: zhangt58/qt-app-builder@v1
        id: appbuild
        with:
          project_file: "mychartapp.pro"
          app_name: "chart-app"
          exec_names: "mychartapp"

      - name: Get the output from qt-app-builder
        run: |
          echo "Self-extract artifacts: ${{ steps.appbuild.outputs.run_filename }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Self-extractable run file
          path: ${{ steps.appbuild.outputs.run_filename }}
          retention-days: 1
