name: Build Qt Projects on Linux

on: [ push ]

#env:
  # Qt project file
  #PRO_NAME: "mychartapp.pro"
  # all executable names
  #EXEC_NAMES: "mychartapp"
  # the main executable name
  #MAIN_EXEC: "mychartapp"
  # app name
  #APP: "chart-app"
  # app description
  #APP_DESC: "A simple chart app with Qt6"
  # folder name for binary files
  #DIST_DIR: "dist"

  # LANG: "C.UTF-8"
  # LC_ALL: "C.UTF-8"

  # TAG
  #TAG_NAME: "${{ github.ref_name }}"

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build a Qt App
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build with my action
        uses: zhangt58/hello-world-docker-action@v3.8
        id: appbuild
        with:
          project_file: "mychartapp.pro"
          app_name: "chart-app"
          exec_names: "mychartapp"
          dist_dir: "dist"

      - name: Get the output from my action
        run: |
          echo "Self-extract artifacts: ${{ steps.appbuild.outputs.run_filename }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Self-extractable run file
          path: ${{ steps.appbuild.outputs.run_filename }}
          retention-days: 1
