name: Build Qt Projects on Linux

on:
  push:
    branches: [ gsl ]

env:
  LANG: "C.UTF-8"
  LC_ALL: "C.UTF-8"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: tonyzhang/focal-builder:5.2
    steps:
      - name: Install dependencies
        run: |
          apt-get update -q -y
          apt-get install -y libpulsedsp
      - name: Check building env
        run: |
          /tmp/squashfs-root/AppRun --version
          /usr/lib/qt-new/bin/qmake --version
          makeself --version
          dos2unix --version
          apt-cache policy libpulsedsp
      - name: Checkout repo
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Check working directory
        run: |
          pwd
          ls -lhtr
      - name: Set Envs
        run: |
          echo "PRO_NAME=mychartapp.pro" >> "$GITHUB_ENV"
          echo "EXEC=mychartapp" >> "$GITHUB_ENV"
          echo "QT_DEPLOYER_PATH=/tmp/squashfs-root/AppRun" >> "$GITHUB_ENV"
          echo "QT_DEPLOYER_OPTS=-bundle-non-qt-libs -no-translations" >> "$GITHUB_ENV"
          echo "QMAKE=/usr/lib/qt-new/bin/qmake" >> "$GITHUB_ENV"
          echo "MAKESELF_PATH=makeself" >> "$GITHUB_ENV"
          echo "MAKESELF_OPTS=--notemp --nox11 --tar-quietly --xz" >> "$GITHUB_ENV"
          echo "SHA_SHORT=$(echo ${{github.sha}} | cut -c1-6)" >> "$GITHUB_ENV"
      - name: Check Envs
        run: |
          echo "$PRO_NAME"
          echo "$EXEC"
          echo "$QT_DEPLOYER_PATH"
          echo "$QT_DEPLOYER_OPTS"
          echo "$QMAKE"
          echo "$MAKESELF_PATH"
          echo "$MAKESELF_OPTS"
      - name: Build binaries
        run: |
          echo "Hello, ${{github.actor}}!"
          "$QMAKE" CONFIG+=release CONFIG+=optimize_full "$PRO_NAME"
          make -j$(cat /proc/cpuinfo | /bin/grep processor | wc -l)

          echo "Create binary tarball"
          mkdir chart-app
          cp -r ${EXEC} chart-app
          cd chart-app
          for app in ${EXEC}
          do
              ${QT_DEPLOYER_PATH} ${app} -qmake=${QMAKE} ${QT_DEPLOYER_OPTS}
              strip --strip-unneeded ${app}
          done
          cat << EOF > run_app.sh
          #!/bin/sh
          cwdir=\`dirname \$0\`
          \${cwdir}/mychartapp
          EOF
          chmod +x run_app.sh

          cd ..; tar cv chart-app | xz -9 > "chart-app_${SHA_SHORT}.orig.tar.xz"

          echo "Create self-extractable script"
          "${MAKESELF_PATH}" ${MAKESELF_OPTS} chart-app "chart-app_${SHA_SHORT}.run" \
            "A simple Chart App with Qt6 " ./run_app.sh
          echo "New version released: ${SHA_SHORT}."

      - name: Output binary packages (1)
        uses: actions/upload-artifact@v4
        with:
          name: Binary tarball
          path: chart-app_${{ env.SHA_SHORT }}.orig.tar.xz
          retention-days: 7

      - name: Output binary packages (2)
        uses: actions/upload-artifact@v4
        with:
          name: Self-extract run file
          path: chart-app_${{ env.SHA_SHORT }}.run"
          retention-days: 7
